### PR TITLE
Basic Django Web Server

### PR DESCRIPTION
**Pull request by erichumphries**
I created a starting place for our web server. It has places to put the html files, css files, and any other static files such as images. Right now, it just displays a basic, example html file. From here, other people will be able to push the front-end files to the server, and we can begin developing the API to be used.

### CODE REVIEW

**Comment by huntnguyen** [comment]
okay with me

**Comment by ghost** [comment]
Looks good

**Comment by marcoalexander** [comment]
Looks good!

**Comment by erichumphries** [comment]
In that case, I'll go ahead and merge the two branches.

**Pull request merged**
